/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.formulariodoencas;

/**
 *
 * @author 05632593029
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPesquisarDoenca = new javax.swing.JButton();
        btnPesquisarSintoma = new javax.swing.JButton();
        btnVincularSintoma = new javax.swing.JButton();
        btnCadastrarDoenca = new javax.swing.JButton();
        btnCadastrarSintoma = new javax.swing.JButton();
        btnIdentificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPesquisarDoenca.setText("Pesquisar Doença");
        btnPesquisarDoenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarDoencaActionPerformed(evt);
            }
        });

        btnPesquisarSintoma.setText("Pesquisar Sintoma");
        btnPesquisarSintoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarSintomaActionPerformed(evt);
            }
        });

        btnVincularSintoma.setText("Vincular Sintomas");
        btnVincularSintoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVincularSintomaActionPerformed(evt);
            }
        });

        btnCadastrarDoenca.setText("Cadastrar Doença");
        btnCadastrarDoenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarDoencaActionPerformed(evt);
            }
        });

        btnCadastrarSintoma.setText("Cadastro Sintomas");
        btnCadastrarSintoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarSintomaActionPerformed(evt);
            }
        });

        btnIdentificar.setText("Identificação de Doenças por Sintomas");
        btnIdentificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIdentificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnIdentificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnPesquisarDoenca)
                                .addGap(18, 18, 18)
                                .addComponent(btnPesquisarSintoma)
                                .addGap(18, 18, 18)
                                .addComponent(btnVincularSintoma))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(btnCadastrarDoenca)
                                .addGap(53, 53, 53)
                                .addComponent(btnCadastrarSintoma)))
                        .addGap(4, 4, 4)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPesquisarDoenca)
                    .addComponent(btnPesquisarSintoma)
                    .addComponent(btnVincularSintoma))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarDoenca)
                    .addComponent(btnCadastrarSintoma))
                .addGap(18, 18, 18)
                .addComponent(btnIdentificar)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarDoencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarDoencaActionPerformed
        // TODO add your handling code here:
        new PesquisarDoenca().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPesquisarDoencaActionPerformed

    private void btnPesquisarSintomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarSintomaActionPerformed
        // TODO add your handling code here:
        new PesquisarSintoma().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPesquisarSintomaActionPerformed

    private void btnVincularSintomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVincularSintomaActionPerformed
        // TODO add your handling code here:
        new VincularSintomas().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVincularSintomaActionPerformed

    private void btnCadastrarDoencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarDoencaActionPerformed
        // TODO add your handling code here:
        new CadastroDoencas().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCadastrarDoencaActionPerformed

    private void btnCadastrarSintomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarSintomaActionPerformed
        // TODO add your handling code here:
        new CadastroSintomas().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCadastrarSintomaActionPerformed

    private void btnIdentificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIdentificarActionPerformed
        // TODO add your handling code here:
        new IdentificacaoDeDoencasPorSintomas().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnIdentificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarDoenca;
    private javax.swing.JButton btnCadastrarSintoma;
    private javax.swing.JButton btnIdentificar;
    private javax.swing.JButton btnPesquisarDoenca;
    private javax.swing.JButton btnPesquisarSintoma;
    private javax.swing.JButton btnVincularSintoma;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
